name: lab2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^0.13.5
  url_launcher: ^6.1.5
  flutter_local_notifications: 18.0.1
  flutterfire_cli: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
